name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

version-resolver:
  major:
    labels: ['major', 'breaking', 'breaking-change']
  minor:
    labels: ['feature', 'enhancement', 'feat']
  patch:
    labels: ['fix', 'bug']
  default: patch

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
no-changes-template: '- No changes'

categories:
  - title: 'Maintenance'
    labels: ['chore', 'deps', 'dependencies', 'maintenance']
  - title: 'Features & Fixes'
    labels: ['feature', 'enhancement', 'feat', 'fix', 'bug']
  - title: 'Other Changes'
    labels: ['*']

category-template: |
  $TITLE

  $CHANGES

template: |
  What's Changed

  $CHANGES

  Deployment Model (Important)

  - **Railway services track the `:prod` image tag**
  - **Only services with code changes in this release receive a new versioned image**
  - Unchanged services continue running their previously deployed image digest

  Docker Images (GHCR)

  Pull images manually (if needed):

  # Raincloud Orchestrator
  ghcr.io/connor-adams/rainbot-raincloud:prod

  # Worker Bots
  ghcr.io/connor-adams/rainbot-rainbot:prod
  ghcr.io/connor-adams/rainbot-pranjeet:prod
  ghcr.io/connor-adams/rainbot-hungerbot:prod

  Versioned Tags

  - Version tags (e.g. `v$RESOLVED_VERSION`) are **only published for services that changed**
  - Do **not** assume every service has a tag for this release

  Railway

  No manual action required. Railway redeploys only affected services via webhook.

  Full Changelog: $PREVIOUS_TAG...v$RESOLVED_VERSION
