name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  ## dYs? What's Changed

  $CHANGES

  ## dY"İ Railway Deployment

  Deploy is gated on release. Stack commits safely, then publish a release when ready:
  - Merge PRs into `main` to accumulate changes
  - Review the draft release notes
  - Publish the release to trigger Railway deploys

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: 'dYs? Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'dY?> Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'dYø Maintenance'
    labels:
      - 'chore'
      - 'maintenance'
      - 'dependencies'
  - title: 'dY"- Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: 'dY" Configuration'
    labels:
      - 'config'
      - 'infrastructure'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
  default: patch

autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
      - 'docs/**/*'
  - label: 'feature'
    branch:
      - '/feature\/.+/'
  - label: 'fix'
    branch:
      - '/fix\/.+/'
      - '/bugfix\/.+/'
  - label: 'chore'
    branch:
      - '/chore\/.+/'
      - '/maintenance\/.+/'
  - label: 'infrastructure'
    files:
      - 'Dockerfile*'
      - '.github/**/*'
      - 'railway*.json'
      - 'turbo.json'

exclude-labels:
  - 'skip-changelog'
